### ISSUE TITLE
Problem with npm run build

### ISSUE THREAD

**Issue by Peech1502** [wprig/wprig#241]
## Issue Overview

wprig does not build my theme
## Describe your environment

I am working on a Mac and i have followed the instructions on wprig.io I am working with VSC 
## Steps to Reproduce

Svens-Mac-mini:peedo svendressler$ sudo npm install
Password:

> fsevents@1.2.3 install /Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.3/fse-v1.2.3-node-v67-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.3 and node@11.4.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/fsevents
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/fsevents
node-pre-gyp ERR! node -v v11.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)

> jpeg-recompress-bin@3.0.1 postinstall /Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/jpeg-recompress-bin
> node lib/install.js

  ✖ Error: EACCES: permission denied, mkdir '/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/jpeg-recompress-bin/vendor'
/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/each-async/node_modules/onetime/index.js:15
                                throw new Error(fnName + ' can only be called once.');
                                ^

Error: callback() can only be called once.
    at onetime (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at /Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:194:15)
    at finishMaybe (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:277:13)
    at DuplexWrapper.emit (events.js:194:15)
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jpeg-recompress-bin@3.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jpeg-recompress-bin@3.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svendressler/.npm/_logs/2018-12-13T19_28_34_199Z-debug.log
Svens-Mac-mini:peedo svendressler$ sudo npm run build

> wprig@1.0.4 build /Users/svendressler/Desktop/wordpress/wp-content/themes/peedo
> gulp

[20:29:01] Failed to load external module @babel/register
[20:29:01] Requiring external module babel-register
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'gulp-image'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/gulpfile.babel.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at loader (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@1.0.4 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wprig@1.0.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svendressler/.npm/_logs/2018-12-13T19_30_05_043Z-debug.log
Svens-Mac-mini:peedo svendressler$

**Comment by brigleb** [comment]
Are you sure you've installed Composer first? I was able to just use `brew install composer` first and skip the overly-complicated instructions on that site, which is nice if you've got Homebrew installed.

**Comment by Peech1502** [comment]
yes i have installed composer first and also homebrew is installed. always the same:

Svens-Mac-mini:peedo svendressler$ sudo npm run build
Password:

> wprig@1.0.4 build /Users/svendressler/Desktop/wordpress/wp-content/themes/peedo
> gulp

[20:07:09] Failed to load external module @babel/register
[20:07:09] Requiring external module babel-register
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'gulp-image'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/gulpfile.babel.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at loader (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/svendressler/Desktop/wordpress/wp-content/themes/peedo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@1.0.4 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wprig@1.0.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svendressler/.npm/_logs/2018-12-18T19_08_19_684Z-debug.log

**Comment by mor10** [comment]
Looks like some dependencies are missing. Try running `npm install` again and see what happens.
