### ISSUE TITLE
Error with matched module on npm run build

### ISSUE THREAD

**Issue by briainod** [wprig/wprig#327]
## Issue Overview

the project won't build due to an error with promiseJS in the matched library.

## Describe your environment

OS X 10.13.6 
PHPStorm 2018.1

## Steps to Reproduce

I've followed the installation steps provided on the main site except for the VSCode ones. Have replaced these steps by setting the composer.json path in Preferences>>Languages & Frameworks>>PHP>Composer. This is the only difference between my setup and that in the tutorials.

I get the following error when trying to build the project:

`> wprig@1.0.4 build /Users/me/Sites/bdstarterrig/wp-content/themes/bdrig
> gulp

[14:45:42] Failed to load external module @babel/register
[14:45:42] Requiring external module babel-register
/Users/me/Sites/bdstarterrig/wp-content/themes/bdrig/node_modules/matched/lib/promise.js:8
module.exports = async function(patterns, options) {
                       ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/me/Sites/bdstarterrig/wp-content/themes/bdrig/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@1.0.4 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wprig@1.0.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

I saw a similar error [here](https://github.com/wprig/wprig/issues/26) and have tried updating node in a variety of ways, the latest of which was force deleting the global node_modules and .npm directories, force uninstalling the package using homebrew and reinstalling it. After this I used a fresh copy of WPRig and restarted PHPStorm to ensure a new instance of the terminal. Same error.

Have tried installing the matched library in the project to see if it would remove the error but it doesn't.

**Comment by briainod** [comment]
Seems my attempts to upgrade node weren't proper, it was still running 6.10.x. Downloaded 10.x instead of installing through Terminal and it's running fine.
