### ISSUE TITLE
Error on npm run dev, v.2.0 branch

### ISSUE THREAD

**Issue by ehowey** [wprig/wprig#340]
## Issue Overview
Getting an error when attempting to use "npm run dev" in the 2.0 branch. "npm run build" works.

Here is the error:
[22:32:19] 'watch' errored after 64 ms
[22:32:19] TypeError: expected a string
    at module.exports (/Users/erichowey/Documents/Local Sites/Eric-Howey-Design/app/public/wp-content/themes/wprig-2.0/node_modules/is-negated-glob/index.js:5:11)
    at sortGlobs (/Users/erichowey/Documents/Local Sites/Eric-Howey-Design/app/public/wp-content/themes/wprig-2.0/node_modules/glob-watcher/index.js:66:18)
    at Array.forEach (<anonymous>)
    at watch (/Users/erichowey/Documents/Local Sites/Eric-Howey-Design/app/public/wp-content/themes/wprig-2.0/node_modules/glob-watcher/index.js:63:18)
    at Gulp.watch (/Users/erichowey/Documents/Local Sites/Eric-Howey-Design/app/public/wp-content/themes/wprig-2.0/node_modules/gulp/index.js:45:10)
    at watch (/Users/erichowey/Documents/Local Sites/Eric-Howey-Design/app/public/wp-content/themes/wprig-2.0/gulp/watch.js:49:2)
    at bound (domain.js:400:14)
    at runBound (domain.js:413:12)
    at asyncRunner (/Users/erichowey/Documents/Local Sites/Eric-Howey-Design/app/public/wp-content/themes/wprig-2.0/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
[22:32:19] 'default' errored after 60 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@2.0.0 dev: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wprig@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/erichowey/.npm/_logs/2019-03-01T05_32_19_895Z-debug.log

This is the debug.log file:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.10.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.7.0
3 info using node@v11.10.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle wprig@2.0.0~predev: wprig@2.0.0
6 info lifecycle wprig@2.0.0~dev: wprig@2.0.0
7 verbose lifecycle wprig@2.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle wprig@2.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/erichowey/Documents/Local Sites/Eric-Howey-Design/app/public/wp-content/themes/wprig-2.0/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle wprig@2.0.0~dev: CWD: /Users/erichowey/Documents/Local Sites/Eric-Howey-Design/app/public/wp-content/themes/wprig-2.0
10 silly lifecycle wprig@2.0.0~dev: Args: [ '-c', 'gulp' ]
11 silly lifecycle wprig@2.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle wprig@2.0.0~dev: Failed to exec dev script
13 verbose stack Error: wprig@2.0.0 dev: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:984:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid wprig@2.0.0
15 verbose cwd /Users/erichowey/Documents/Local Sites/Eric-Howey-Design/app/public/wp-content/themes/wprig-2.0
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/11.10.1/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v11.10.1
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error wprig@2.0.0 dev: `gulp`
22 error Exit status 1
23 error Failed at the wprig@2.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

## Describe your environment
VS Code
Mac OS 10.13 High Sierra
Node.js v.11.10.1
npm v.6.7.0
composer v1.8.4
Gulp CLI 2.0.1
Gulp Local v.4.0.0
Latest version of Xcode

I do use Homebrew to install node and composer.  Wp-Rig 1.0.4 has been working fine for me so I do not think it is a problem with the development environment...at least I do not think so.

## Steps to Reproduce
I was interested to test out the 2.0 branch to see what it was like.  Clean install, downloaded fresh today. Ran 'npm install' with no significant errors.  I can do npm run build and get a useable theme so I think this has something to do with the watch process in Gulp from what I can surmise. 

## Expected Behavior
The npm run dev command to work.

## Current Behavior
See error above.

## Possible Solution
I did some brief googling of the error codes with little luck.

**Comment by ehowey** [comment]
Okay - so...I was able to get it working by commenting out one line of code...so I assume that is where the error was coming from.  
Line 49, in watch.js
"gulpWatch([paths.styles.src, paths.styles.cssCustomProperties, paths.styles.cssCustomMedia], series( styles ) );"

I am not sure why this is giving me the problem but it is.

I am able to get it running somewhat if I modify this line of code to be:

"gulpWatch(paths.styles.src, series(styles, reload));"

**Comment by ehowey** [comment]
Please be aware I am a bit green when it comes to mucking around deep in code - usually just CSS/HTML and a small amount of PHP and JS.  

I think this error, for me, was relating to the following change:

https://github.com/wprig/wprig/commit/c7931c69458a0ba846d1f7592686c59edd8f6b92

The watch process is looking for the custom properties and custom media files but those have now been ignored which is causing a error in that line 49 process.

**Comment by ehowey** [comment]
So to get it working again I had to revert to the following code in constant.js (starting line 67), not 100% sure why but form what I can gather the recent changes to that file were causing my original error above.

styles: {
		cssCustomProperties: `${assetsDir}/css/src/custom-properties.css`,
		cssCustomMedia: `${assetsDir}/css/src/custom-media.css`,
		src: `${assetsDir}/css/src/**/*.css`,
		sass: `${assetsDir}/css/src/**/*.scss`,
		dest: `${assetsDir}/css/`
	},

**Comment by ehowey** [comment]
This can be closed - fixed with the updates today.  Thank-you!
