### ISSUE TITLE
TypeError: path.replace is not a function

### ISSUE THREAD

**Issue by carolinan** [wprig/wprig#498]
## Issue Overview

After installing 2.0 using `npm run rig-init`, I try to use `npm run dev` but I am getting the following error:

`[04:36:17] Starting 'watch'...

[04:36:17] 'watch' errored after 2.42 ms

[04:36:17] TypeError: path.replace is not a function
    at replace (D:\reviewdock\wp-app\wp-content\themes\wprig-poenari\gulp/utils.js:122:14)
    at watch (D:\reviewdock\wp-app\wp-content\themes\wprig-poenari\gulp/watch.js:26:31)
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at asyncRunner (D:\reviewdock\wp-app\wp-content\themes\wprig-poenari\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)

[04:36:17] 'default' errored after 26 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wprig@2.0.0 dev: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wprig@2.0.0 dev script.`

## Describe your environment

Windows 10 PRO os version 17763.503
PHP Version 7.2.13
Composer version 1.8.0
npm version 6.9.0
gulp: CLI version: 2.2.0  Local version: 4.0.2
Node v10.14.1
Terminal: windows powershell

## Steps to Reproduce

1. Download zip file from github
2. Unzip, add folder to theme directory, rename it to wprig-themeslug, (wprig-poenari) updated config file.
3. Use  npm run rig-init
4. Use npm run dev

_Note that I did not do any changes except to the config file where I changed the theme name, slug and namespace._

## Expected Behavior

I expect there to be no errors.

## Current Behavior

See the error above.

**Comment by ataylorme** [comment]
@carolinan can you test #499 to see if it fixes the issue for you?
