### ISSUE TITLE
Failed at the wprig@2.0.1 rig-init script

### ISSUE THREAD

**Issue by Netyson** [wprig/wprig#620]
### Issue Overview
First of all, i want to thank you guys for the great work. I am starting right now to learn and understanding wprig. Unfortunately i missed already the installation.
I was following the GitHub guide: https://github.com/wprig/wprig
At the stage: ` npm run rig-init` i get some errors and the process stooped. 

Error:
`21 error errno 255`
`22 error wprig@2.0.1 rig-init: npm install && composer install`
`22 error Exit status 255`
`23 error Failed at the wprig@2.0.1 rig-init script.`
`23 error This is probably not a problem with npm. There is likely additional logging output above.`

## Describe your environment
vcode
Ubuntu 19.10 Virtual Box VM
PHP 7.3.11-0ubuntu0.19.10.1 (cli) 
LocalByFlyweel

## Steps to Reproduce

1. Clone this repo and checkout the v2.0 branch.
2. Run npm run rig-init.

## Expected Behavior
I hoped that the run process would go without errors. If i try to activate the wprig theme in the wp back-end i get some errors as well. 

## Current Behavior
![screenshot](https://user-images.githubusercontent.com/29839812/69097182-505da100-0a56-11ea-8585-2748a84f8070.png)

Debug Log:

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   '/home/mangowambo/.nvm/versions/node/v13.1.0/bin/node',
> 1 verbose cli   '/home/mangowambo/.nvm/versions/node/v13.1.0/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'rig-init'
> 1 verbose cli ]
> 2 info using npm@6.12.1
> 3 info using node@v13.1.0
> 4 verbose run-script [ 'prerig-init', 'rig-init', 'postrig-init' ]
> 5 info lifecycle wprig@2.0.1~prerig-init: wprig@2.0.1
> 6 info lifecycle wprig@2.0.1~rig-init: wprig@2.0.1
> 7 verbose lifecycle wprig@2.0.1~rig-init: unsafe-perm in lifecycle true
> 8 verbose lifecycle wprig@2.0.1~rig-init: PATH: /home/mangowambo/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/mangowambo/Local Sites/arteeo/app/public/wp-content/themes/wprig/node_modules/.bin:/home/mangowambo/.nvm/versions/node/v13.1.0/bin:/home/mangowambo/Documents/composer-dir:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 9 verbose lifecycle wprig@2.0.1~rig-init: CWD: /home/mangowambo/Local Sites/arteeo/app/public/wp-content/themes/wprig
> 10 silly lifecycle wprig@2.0.1~rig-init: Args: [ '-c', 'npm install && composer install' ]
> 11 silly lifecycle wprig@2.0.1~rig-init: Returned: code: 255  signal: null
> 12 info lifecycle wprig@2.0.1~rig-init: Failed to exec rig-init script
> 13 verbose stack Error: wprig@2.0.1 rig-init: `npm install && composer install`
> 13 verbose stack Exit status 255
> 13 verbose stack     at EventEmitter.<anonymous> (/home/mangowambo/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:210:5)
> 13 verbose stack     at ChildProcess.<anonymous> (/home/mangowambo/.nvm/versions/node/v13.1.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:210:5)
> 13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
> 14 verbose pkgid wprig@2.0.1
> 15 verbose cwd /home/mangowambo/Local Sites/arteeo/app/public/wp-content/themes/wprig
> 16 verbose Linux 5.3.0-23-generic
> 17 verbose argv "/home/mangowambo/.nvm/versions/node/v13.1.0/bin/node" "/home/mangowambo/.nvm/versions/node/v13.1.0/bin/npm" "run" "rig-init"
> 18 verbose node v13.1.0
> 19 verbose npm  v6.12.1
> 20 error code ELIFECYCLE
> 21 error errno 255
> 22 error wprig@2.0.1 rig-init: `npm install && composer install`
> 22 error Exit status 255
> 23 error Failed at the wprig@2.0.1 rig-init script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 255, true ]

## Possible Solution
I am very thankful for any advise :)

## Related Issues and/or PRs

> I found this issue #412 for PHP 7.3 maybe my error is related. 

Edit: I think we can ignore that, i also tested the installation with PHP 7.2 and got the same errors.

**Comment by Netyson** [comment]
Dear Community, 
Unfortunately i dont get wp-rig to run on my **Ubuntu VM**. After several tries i had also problems with (LocalByFlyweel) the reason for that was that Apache was running and Local had some name conflicts.  After deactivating apachte (sudo systemctl status apache2 & sudo systemctl stop apache2) the Local software worked again. 

I started to think my setup was wrong, so i tried it on a **Windows environment**.
The good news is, on my main OS (Windows) and after clean install
NPM, GULP and Composer (via git bash for Windows --> https://gitforwindows.org) with some checks on the Windows Path. i got it to work.

So the issue can be closed.
