### ISSUE TITLE
issue with launching wp rig from my terminal terminal 

### ISSUE THREAD

**Issue by malsharifm** [wprig/wprig#686]
## Issue Overview
I'm getting an error when trying to launch wp rig from my terminal. As far as I understood, wp rig doesn't work inside wordpress out of the box and it needs to be connected in order to perform changes.  I'm trying to achieve this connection but I keep getting an error 

## Describe your environment
I'm using brackets as my code editor. 
Composer has been installed globally and I don't have any problem running it 

## Steps to Reproduce
I'm following mor10's course "WordPress: Building Progressive Themes with WP Rig". I have performed all the tasks leading to activation of the theme. When I run this: **npm run dev** in my terminal I get an error. Here is the debug message:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.9
3 info using node@v14.15.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle wprig@2.0.1~predev: wprig@2.0.1
6 info lifecycle wprig@2.0.1~dev: wprig@2.0.1
7 verbose lifecycle wprig@2.0.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle wprig@2.0.1~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Applications/MAMP/htdocs/wordpress/wp-content/themes/wprig-master/node_modules/.bin:/anaconda/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle wprig@2.0.1~dev: CWD: /Applications/MAMP/htdocs/wordpress/wp-content/themes/wprig-master
10 silly lifecycle wprig@2.0.1~dev: Args: [ '-c', 'gulp' ]
11 silly lifecycle wprig@2.0.1~dev: Returned: code: 1  signal: null
12 info lifecycle wprig@2.0.1~dev: Failed to exec dev script
13 verbose stack Error: wprig@2.0.1 dev: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid wprig@2.0.1
15 verbose cwd /Applications/MAMP/htdocs/wordpress/wp-content/themes/wprig-master
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v14.15.3
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error wprig@2.0.1 dev: `gulp`
22 error Exit status 1
23 error Failed at the wprig@2.0.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
 

How to fix this?

**Comment by jacklowrie** [comment]
@malsharifm did you run `composer install` and `npm install`, or `npm run rig-init` from inside your wprig directory before running `npm run dev`?
