### ISSUE TITLE
Issue when using npm run rig-init

### ISSUE THREAD

**Issue by DaSaRProductions** [wprig/wprig#687]
## Issue Overview
Issue when using npm run rig-init

## Describe your environment
iMac - macOS Big Sur 11.2.1
MAMP PRO - Version 6.3.1
Visual Studio Code - Version 1.54.1
Running command in either VSC or Terminal

## Steps to Reproduce
Response from Terminal
> wprig@2.0.1 rig-init /Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig
> npm install && composer install

> fsevents@1.2.8 install /Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v83-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.8 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
SOLINK_MODULE(target) Release/.node
CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:2818:
../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated:
Use GetBackingStore. See http://crbug.com/v8/9908.
[-Wdeprecated-declarations]
data = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:5272:3: note:
'GetContents' has been explicitly marked deprecated here
V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8config.h:402:39: note:
expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
^
../fsevents.cc:43:32: error: no template named 'Handle' in namespace 'v8'
static void Initialize(v8::Handle<v8::Object> exports);
~~~~^
In file included from ../fsevents.cc:73:
../src/constants.cc:89:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagNone").ToLoca...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:90:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMustScanSubDi...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:91:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUserDropped")...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:92:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagKernelDropped...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:93:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagEventIdsWrapp...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:94:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagHistoryDone")...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:95:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagRootChanged")...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:96:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMount").ToLoc...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:97:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUnmount").ToL...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:98:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemCreated")...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:99:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRemoved")...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:100:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemInodeMeta...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:101:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRenamed")...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:102:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemModified"...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:103:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemFinderInf...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:104:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemChangeOwn...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:105:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemXattrMod"...
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
In file included from ../fsevents.cc:73:
../src/constants.cc:106:11: error: no matching member function for call to 'Set'
object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsFile")....
~~~~~~~~^~~
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3670:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
^
/Users/davidvanakkeren/Library/Caches/node-gyp/14.15.4/include/node/v8.h:3673:37: note:
candidate function not viable: requires 3 arguments, but 2 were provided
V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:315:20)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node --module_name=fse --module_path=/Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack at ChildProcess.<anonymous> (/Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 20.3.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node --module_name=fse --module_path=/Users/davidvanakkeren/Dropbox (Mktg)/MAMP/htdocs/wprigTest/wp-content/themes/wprig/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN eslint-plugin-jsx-a11y@6.2.1 requires a peer of eslint@^3 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@7.13.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-hooks@1.6.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 1925 packages in 12.39s

13 packages are looking for funding
run `npm fund` for details

found 726 vulnerabilities (699 low, 26 moderate, 1 high)
run `npm audit fix` to fix them, or `npm audit` for details
sh: composer: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! wprig@2.0.1 rig-init: `npm install && composer install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the wprig@2.0.1 rig-init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/davidvanakkeren/.npm/_logs/2021-03-11T16_27_32_139Z-debug.log

**Comment by jacklowrie** [comment]
@DaSaRProductions it looks like you might not have composer installed properly on your machine:
> sh: composer: command not found

Try installing composer, and running the command again and see how that goes.
