### ISSUE TITLE
PHP Fatal error on fresh install (`WP_Rig\WP_Rig\JavaScript\Component`)

### ISSUE THREAD

**Issue by bmarshall511** [wprig/wprig#820]
1. Fresh WP site (using Local WP)
2. Downloaded the latest version (https://github.com/wprig/wprig/releases/tag/v2.2.1)
3. Followed instructions here: https://wprig.io/#install
4. When activating the theme got a fatal error that crashed the site:

```
[14-Oct-2022 15:57:42 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_Rig\WP_Rig\JavaScript\Component' not found in /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-content/themes/wprig/inc/Theme.php:159
Stack trace:
#0 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-content/themes/wprig/inc/Theme.php(46): WP_Rig\WP_Rig\Theme->get_default_components()
#1 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-content/themes/wprig/inc/functions.php(21): WP_Rig\WP_Rig\Theme->__construct()
#2 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-content/themes/wprig/functions.php(66): WP_Rig\WP_Rig\wp_rig()
#3 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-settings.php(566): include('/Users/benmarsh...')
#4 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-config.php(104): require_once('/Users/benmarsh...')
#5 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-load.php(50): require_once('/Users/benmarsh...')
#6 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/ in /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-content/themes/wprig/inc/Theme.php on line 159
[14-Oct-2022 15:57:43 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_Rig\WP_Rig\JavaScript\Component' not found in /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-content/themes/wprig/inc/Theme.php:159
Stack trace:
#0 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-content/themes/wprig/inc/Theme.php(46): WP_Rig\WP_Rig\Theme->get_default_components()
#1 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-content/themes/wprig/inc/functions.php(21): WP_Rig\WP_Rig\Theme->__construct()
#2 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-content/themes/wprig/functions.php(66): WP_Rig\WP_Rig\wp_rig()
#3 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-settings.php(566): include('/Users/benmarsh...')
#4 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-config.php(104): require_once('/Users/benmarsh...')
#5 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-load.php(50): require_once('/Users/benmarsh...')
#6 /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/ in /Users/benmarshall/Local Sites/wordpress-sandbox/app/public/wp-content/themes/wprig/inc/Theme.php on line 159
```

**Comment by robruiz** [comment]
Thank you for reporting this. A recent bug fix rushed code review. This has been fixed. It was only like this for 1 day
